#!/bin/bash
set -e

echo "=== Installing Flutter (stable) ==="
git clone https://github.com/flutter/flutter.git --depth 1 -b stable "$HOME/flutter"
export PATH="$HOME/flutter/bin:$PATH"
flutter config --no-analytics --no-cli-animations

echo "=== Generating lib/config/env.dart from environment variables ==="
mkdir -p lib/config
cat > lib/config/env.dart << EOF
// Auto-generated by cloudflare-build.sh — DO NOT COMMIT
class Env {
  static const String workerBaseUrl = '${WORKER_BASE_URL}';
}
EOF

echo "=== flutter pub get ==="
flutter pub get

echo "=== flutter build web ==="
flutter build web --release

echo "=== Build complete: build/web ==="
